### ISSUE TITLE
Akward math/equation in ch.6

### ISSUE THREAD

**Issue by ghost** [team6749/FRC-Coding-Documentation#11]
I've read through the briefly covered equation of chapter 6 a couple of times now, and I still do not really understand it. It would seem the equation is an attempted deriving of the formula for the circumference of a circle in order to calculate the length of the arc. However, if that is the case, then the formula would be: $$2 \pi r \cdot 90/360$$ This is because you are trying to get a fraction of the entire circumference of the circle. I also do not believe it is useful to include tau (or $\uptau$) in this, since it both confuses the equation, and from what I have read, it is equal to $2pi$, which is not what the documentation suggests, $2/pi$.

For reference, the equation in chapter 6 is: $$\frac{radius*\uptau}{rotation/360}$$
This could also, though unlikely, be an issue with obsidian processing latex, since I am viewing the code in github and raw markdown.

**Comment by ghost** [comment]
The code below the explanation also seems to have a different equation, in which the math does seem to check out. (though $2*\pi/4$ with division should leave just $\pi /2$)
```java
//Distances for the turn
static double leftWheelDistance = 3*2*Math.PI/4;
static double rightWheelDistance = 2*Math.PI/4;
```

**Comment by mootw** [comment]
tau is used to introduce a cool math variable, i mention what the value is below the equation. it is also quite clean looking so i just used it because i like it and it is a good introduction to how variables can compound! it does appear like the equation is messed up, it should be: $$\frac{radius*\uptau}{360/rotation}$$
the rotation and 360 values got flipped. I will make sure to fix that asap!

for the equations in the code they also do appear correct to me after checking it again. I intentionally do not simplify them in the code here because it is introductory and i want it to be extremely clear where the numbers come from in the equation! this can actually be a good practice even for final code in the robot. you will see equations that are intentionally not simplified a large amount to make it clear where it is derived from. it **can** make the code easier to read with a meaningless performance cost.

i also intend to rename the "rotation" part to something like "rotation degrees" to be more clear about the units of the variable.

**Comment by 6749computers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [fix incorrect docs equation](https://trello.com/c/14VkZ7C4/37-fix-incorrect-docs-equation)
